sample/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search/$', views.runFoxhound, name='search'),
]

sampler/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^sample/', include('sample.urls', namespace="sample")),
]

sample/models.py
from django.db import models
from djangotoolbox.fields import ListField

# Create your models here.
class QueryModel(models.Model):
    sessionname = models.TextField()
    savedimages = ListField()
    savedtags = ListField()
    def __str__(self):
        return self.sessionname

sample/views.py
from django.shortcuts import render
from django.http import HttpResponse
import pycurl, json, StringIO
import json, ast
# Use requests to query the API website and assign results to a variable
import requests
from .models import QueryModel


def links(mined_urls, results, resultTags):
    try:
        z = 0
        for z in range(z, len(results["items"][z])):
            mined_urls.append(results["items"][z]["link"].encode("ascii", "ignore"))
            resultTags.append(results["items"][z]["title"].encode("ascii", "ignore"))
            resultTags.append(results["items"][z]["snippet"].encode("ascii", "ignore"))
    except KeyError, e:
        print e


def index(request):
    return render(request, 'sample/index.html')

def runFoxhound(request):
    index_num = 1  # index_num represent the number of iterations of the startIndex parameter in order to get 100 images
    mined_urls = []
    key = "AIzaSyAjlYK7bngoiPxBE9koo09RWZK3oTNR0mo"
    cx = "008280251192147562951:rghr1k2p058"
    url = "https://www.googleapis.com/customsearch/v1"
    activeRecord = []
    # Append input parameters
    inputTags = []
    if 'query1' in request.POST:
        inputTags.append(request.POST['query1'].encode('ascii', 'ignore'))
    if 'query2' in request.POST:
        inputTags.append(request.POST['query2'].encode('ascii', 'ignore'))
    if 'query3' in request.POST:
        inputTags.append(request.POST['query3'].encode('ascii', 'ignore'))

    if len(inputTags) != 0:
        activeRecord = QueryModel.objects.create(savedtags = inputTags)
        activeRecord.save()
        activeRecord.sessionname = str(activeRecord.id)
        activeRecord.save()
    else:
        activeRecord = QueryModel.objects.get(sessionname=str(request.POST['sessionname']))
        inputTags = ast.literal_eval(json.dumps(activeRecord.savedtags))

    if 'query4' in request.POST:
        inputTags.append(request.POST['query4'].encode('ascii', 'ignore'))
    if 'query5' in request.POST:
        inputTags.append(request.POST['query5'].encode('ascii', 'ignore'))
    if 'query6' in request.POST:
        inputTags.append(request.POST['query6'].encode('ascii', 'ignore'))

    i = 0
    activeRecord.savedtags = inputTags;
    activeRecord.save()

    # Need to locate the top results per keyword into the top results in total
    # Also need to associate images with the keywords and have a way to have the image
    # impact the added keyword

    resultTags = []

    for i in range(i, len(inputTags)):
        parameters = {"q": inputTags[i],
                      "cx": cx,
                      "key": key,
                      "searchType": "image",
                      "start": 1,
                      }
        page = requests.request("GET", url, params=parameters)
        results = json.loads(page.text)
        links(mined_urls, results, resultTags)

    print 'Number of urls ' + str(len(mined_urls))

    context = {
        'queryImageUrls': '',
        'resultImageUrls': mined_urls,
        'sessionid': activeRecord.sessionname,
        'initialTags': inputTags,
        'resultTags': resultTags
    }

    return render(request, 'sample/search.html', context)

sample/templates/sample/index.html
<html>
<head>
    {% load staticfiles %}
    <title>Welcome to the Foxhound search.</title>
    <link rel="stylesheet" type="text/css" href="{% static 'sample/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'sample/image-picker.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'sample/jquery.tag-editor.css' %}" />
</head>
<body>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<h1>Start new search</h1>

<h2>Search parameters</h2>

<form action="{% url 'sample:search' %}" method="post">
    {% csrf_token %}
    <p>Search term 1:</p>
    <input type="text" name="query1" id="txtQuery1" />
    <p>Search term 2:</p>
    <input type="text" name="query2" id="txtQuery2" />
    <p>Search term 3:</p>
    <input type="text" name="query3" id="txtQuery3" />
    <br>
    <input type="submit" value="Search" />
</form>

</body>
</html>

sample/templates/sample/search.html
<html>
<head>
    {% load staticfiles %}
    <title>Welcome to the Foxhound search.</title>
    <link rel="stylesheet" type="text/css" href="{% static 'sample/style.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'sample/image-picker.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'sample/jquery.tag-editor.css' %}" />
</head>
<body>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<h1>Search Session {{ sessionid }}</h1>

<h2>Search parameters</h2>

<form action="{% url 'sample:search' %}" method="post">
    {% csrf_token %}
    <h3>Images</h3>
    <select id="queryImages" multiple="multiple" class="image-picker show-html">
      {% for url in queryImageUrls %}
          <option data-img-src="{{ url }}" value="{{ url }}">{{ url }}</option>
      {% endfor %}
    </select>
    <h3>Searched Keywords</h3>
    <textarea id="queryKeywords"></textarea>
    <h3>New Keywords</h3>
    <p>Search term 1:</p>
    <input type="text" name="query4" />
    <p>Search term 2:</p>
    <input type="text" name="query5" />
    <p>Search term 3:</p>
    <input type="text" name="query6" />
    <br>
    <input type="hidden" name="sessionname" value="{{ sessionid }}" />
    <input type="submit" value="Search" />
</form>

<h2>Search results</h2>

<textarea id="resultKeywords"></textarea>

<select id="resultImages" multiple="multiple" class="image-picker show-html">
  {% for url in resultImageUrls %}
      <option data-img-src="{{ url }}" value="{{ url }}">{{ url }}</option>
  {% endfor %}
</select>

<script type="text/javascript" src="https://code.jquery.com/jquery-2.1.4.js"></script>
<script type="text/javascript" src="{% static 'sample/image-picker.js' %}"></script>
<script type="text/javascript" src="{% static 'sample/jquery.caret.js' %}"></script>
<script type="text/javascript" src="{% static 'sample/jquery.tag-editor.min.js' %}"></script>
<script type="text/javascript">
    document.addEventListener("DOMContentLoaded", function(event) {
        $("#queryImages").imagepicker();
        $("#resultImages").imagepicker();
        $('#queryKeywords').tagEditor({
            clickDelete: true,
            initialTags: {{ initialTags|safe }},
            placeholder: 'Enter tags ...'
        });
        $('#resultKeywords').tagEditor({
            clickDelete: true,
            initialTags: {{ resultTags|safe }},
            placeholder: 'Enter tags ...'
        });
    });
</script>


</body>
</html>